### ISSUE TITLE
Main instance sometimes doesn't show any result

### ISSUE THREAD

**Issue by sith-on-mars** [Extravi/araa-search#102]
First, I'd like to say a big thank you for your incredible work!

The main instance sometimes doesn't show any result. It happened right now and at least once a few days ago. Is there a rate limit on the main instance? Thanks!

**Comment by Extravi** [comment]
Yes, I know I just changed VPS providers today and did some testing. The main instance was rate-limited, and I shut it down for now until it was no longer rate-limited. When it's back up, the instance should be faster because the VPS hardware is better this time.

**Comment by sith-on-mars** [comment]
Brilliant! Thanks for explaining.

**Comment by Extravi** [comment]
its back and fixed now
