### ISSUE TITLE
Plans for adding new search engines

### ISSUE THREAD

**Issue by amogusussy** [Extravi/araa-search#105]
In #103, you mentioned that in order to prevent no results being returned because of rate limiting, you'll implement other search engines to act as a backup.

Here's a template that I've came up with for the results:
```
{
  "wiki": {
    "title": "String",
    "description": "String",
    "link": "String",
    "image": "String"
  },
  "results": [
    {
      "title": "String",
      "description": "String",
      "link": "String",
      "has_sublinks": Bool,
      "sublinks": [
        {
          "title": "String",
          "description": "String",
          "link": "String"
        }
      ]
    }
  ]
}

```
Then we can just edit the `results.html` file to use this format, and it'll be much easier to implement newer engines.

Each engine should have its own file in `src/textEngines/{engine}.py`, and then get called in the textResults.py file.

**Comment by Extravi** [comment]
honestly i was just using the search thing then google blocked it its very annoying i should try to fix this asap

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/e363e387-ef2e-4eb6-b38c-5678d46e3bd2)

**Comment by Extravi** [comment]
it was working before that 
![image](https://github.com/Extravi/araa-search/assets/98912029/4f248649-d283-45ce-a2ed-9665165a748c)

**Comment by Extravi** [comment]
i did find this post by 2captcha not long ago and it has some useful info there is one more post but i cannot find it atm 
![image](https://github.com/Extravi/araa-search/assets/98912029/fc0c222c-bea1-473d-ac55-fb400b79f261)
https://2captcha.com/blog/google-sepr-recaptcha-june-2022

**Comment by Extravi** [comment]
i know it said something about sending request with cookies like the "NID" cookie etc and how the url should look to avoid getting detected

**Comment by Extravi** [comment]
you would need a web driver to capture thos cookies so you can send it in request

**Comment by Extravi** [comment]
I know that my instance processes 9.3k uncached requests, like searches, images, etc., every 24 hours, but as this project grows and I start to process more requests, it's going to get less reliable, so I'll need to try my best to work on making it much more reliable over time.

**Comment by Extravi** [comment]
I do not record any logs on my instance, but the Cloudflare proxy logs the number of requests, not the request made.

**Comment by Extravi** [comment]
Also, because I have one server in Germany, it needs to be behind a CDN for both speed and security reasons.

**Comment by Extravi** [comment]
Also, I'm sure using Cloudflare is fine; I don't really see it as a privacy concern. It's definitely better than sending requests directly to Google. Cloudflare offers a free version of their proxy to test updates before pushing them to their paid clients and users. I don't think Cloudflare records the request made through their proxies, and I'm sure that isn't legal. I think they use free users to test the updates made to their proxy or CDN service, so it won't impact the paid clients or companies that use them.

**Comment by Extravi** [comment]
> Also, because I have one server in Germany, it needs to be behind a CDN for both speed and security reasons.

I have one good server in Germany behind a CDN because it's more cost-efficient, and I have more server resources available for that instance as a result. 4 cores, 8 GB of RAM. Then the network traffic is optimized using Cloudflare. The only thing that seems slow for me is autocomplete here in Canada, but I might have a fix for that soon.

**Comment by Extravi** [comment]
im adding support for a captcha solver so i can use it on my instance 

![image](https://github.com/Extravi/araa-search/assets/98912029/02057d19-c31f-4271-8981-7da56400f558)

**Comment by Extravi** [comment]
in my test it cost like 1 cent pre captcha and thats only when the abuse cookie expires

**Comment by Extravi** [comment]
so it would last a very long time and cost less then any api would

**Comment by Extravi** [comment]
this will be a setting people can use in the config if they want to enable captcha solver support with their own api key

**Comment by Extravi** [comment]
![o6xypg00uac91](https://github.com/Extravi/araa-search/assets/98912029/69740858-f6dc-4d86-b6f5-cd244c6c6a74)

**Comment by Extravi** [comment]
> im adding support for a captcha solver so i can use it on my instance
> 
> ![image](https://private-user-images.githubusercontent.com/98912029/293628130-02057d19-c31f-4271-8981-7da56400f558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODE0ODUsIm5iZiI6MTcwNDE4MTE4NSwicGF0aCI6Ii85ODkxMjAyOS8yOTM2MjgxMzAtMDIwNTdkMTktYzMxZi00MjcxLTg5ODEtN2RhNTY0MDBmNTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA3Mzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MmM3NmZiNjQ4YjJkNjg4MzVhNDMyYzAzOTBiN2ZkMjI0MGE0NjQ3MTkxNWI4MTU2YmNiNzY2NGQxNWJmMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t7ujjCEt2sxATzCDVoY3DAsF40SFsg8B9ZXfjGIZCC4)

https://github.com/Extravi/araa-search/commit/bf83d6bf325d72e7ab9b597cb25e4bf3b68d66fc

its been added

**Comment by Extravi** [comment]
i added the captcha solver but it has an issue it does not work with more then one worker because the variables are not shared in memory until i find a way to fix it i will only be using one worker on my instance

**Comment by Extravi** [comment]
if you know how to share the variables for the captcha solver please let me know or open a pull request for it

**Comment by Extravi** [comment]
one worker and 1 thread

**Comment by Extravi** [comment]
i have added the captcha solver to Araa fixed all bugs with it and its active and running on my instance

**Comment by Extravi** [comment]
its bug free and works with all workers
