### ISSUE TITLE
Cloudflare error 523: origin is unreachable on the main instance.

### ISSUE THREAD

**Issue by amogusussy** [Extravi/araa-search#107]
When you try to search anything in araa, it shows this:
![Image showing Cloudflare error message 523](https://github.com/Extravi/araa-search/assets/83502633/633b577c-af9e-458f-ab93-5ce37c73869a)
And the main page is a version thats been archived by cloudflare.

**Comment by TEMtheLEM** [comment]
Extravi told me that he shut the main instance down yesterday as it was being attacked by a large botnet. Let's hope this is temporary.

**Comment by Extravi** [comment]
yeah I'll bring it back up soon
