### ISSUE TITLE
Changes to how requests are made.

### ISSUE THREAD

**Issue by Extravi** [Extravi/araa-search#108]
Requests made using makeHTMLRequest should look something like this to the server, making them more reliable, and when possible, it will send available cookies to Google if 2Captcha support is enabled.
![image](https://github.com/Extravi/araa-search/assets/98912029/51d048f5-186a-4473-aabc-53f36d82cd5f)

**Comment by Extravi** [comment]
```python
def makeHTMLRequest(url: str):
    # block unwanted request from an edited cookie
    domain = unquote(url).split('/')[2]
    if domain not in WHITELISTED_DOMAINS:
        raise Exception(f"The domain '{domain}' is not whitelisted.")

    # get google cookies
    with open("./2captcha.json", "r") as file:
        data = json.load(file)
    GOOGLE_OGPC_COOKIE = data["GOOGLE_OGPC_COOKIE"]
    GOOGLE_NID_COOKIE = data["GOOGLE_NID_COOKIE"]
    GOOGLE_AEC_COOKIE = data["GOOGLE_AEC_COOKIE"]
    GOOGLE_1P_JAR_COOKIE = data["GOOGLE_1P_JAR_COOKIE"]
    GOOGLE_ABUSE_COOKIE = data["GOOGLE_ABUSE_COOKIE"]

    # Choose a user-agent at random
    user_agent = random.choice(user_agents)
    headers = {
        "User-Agent": user_agent,
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-US,en;q=0.5",
        "Dnt": "1",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "none",
        "Sec-Fetch-User": "?1",
        "Upgrade-Insecure-Requests": "1"
    }

    cookies = {
        "OGPC": f"{GOOGLE_OGPC_COOKIE}",
        "NID": f"{GOOGLE_NID_COOKIE}",
        "AEC": f"{GOOGLE_AEC_COOKIE}",
        "1P_JAR": f"{GOOGLE_1P_JAR_COOKIE}",
        "GOOGLE_ABUSE_EXEMPTION": f"{GOOGLE_ABUSE_COOKIE}"
    }

    # Force all requests to only use IPv4
    requests.packages.urllib3.util.connection.HAS_IPV6 = False
    
    # Grab HTML content with the specific cookie
    html = requests.get(url, headers=headers, cookies=cookies)

    # Return the BeautifulSoup object
    return BeautifulSoup(html.text, "lxml")

**Comment by Extravi** [comment]
this might be a useful cookie to add 
![image](https://github.com/Extravi/araa-search/assets/98912029/a87a09cc-3746-438c-bbeb-63b8a8f2edd0)

**Comment by amogusussy** [comment]
Here's a few changes I'd add:

```
from urllib.parse import urlparse


# Force all requests to only use IPv4
requests.packages.urllib3.util.connection.HAS_IPV6 = False

def makeHTMLRequest(url: str, is_google=False):
    # block unwanted request from an edited cookie
    domain = urlparse(url).netloc
    if domain not in WHITELISTED_DOMAINS:
        raise Exception(f"The domain '{domain}' is not whitelisted.")

    if is_google:
        # get google cookies
        with open("./2captcha.json", "r") as file:
            data = json.load(file)
        cookies = {
            "OGPC": data["GOOGLE_OGPC_COOKIE"],
            "NID": data["GOOGLE_NID_COOKIE"],
            "AEC": data["GOOGLE_AEC_COOKIE"],
            "1P_JAR": data["GOOGLE_1P_JAR_COOKIE"],
            "GOOGLE_ABUSE_EXEMPTION": data["GOOGLE_ABUSE_COOKIE"]
        }
    else:
        cookies = {}

    headers = {
        "User-Agent": random.choice(user_agents),  # Choose a user-agent at random
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-US,en;q=0.5",
        "Dnt": "1",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "none",
        "Sec-Fetch-User": "?1",
        "Upgrade-Insecure-Requests": "1"
    }

    # Grab HTML content with the specific cookie
    html = requests.get(url, headers=headers, cookies=cookies)

    # Return the BeautifulSoup object
    return BeautifulSoup(html.text, "lxml")
```

This sets `requests.packages.urllib3.util.connection.HAS_IPV6` before the function, because it only needs to be set once.
Uses urlparse rather than splitting strings.
Only uses the cookies if the the function is called as makeHTMLRequest(url, is_google=True), so other requests don't send unnecessary cookies.
And removes a few one time use variables because they don't need to be variables.

**Comment by Extravi** [comment]
there will be more changes in the next few days

**Comment by amogusussy** [comment]
Also, the Accept header accepts `*/*`, so all the other MIME types don't need to be specified.

**Comment by Extravi** [comment]
I'm running tests on various capacha blocked vpn connections to see what headers and cookies that will make the request more reliable

**Comment by Extravi** [comment]
> Also, the Accept header accepts `*/*`, so all the other MIME types don't need to be specified.

I'm still going to specify it just in case and I'll continue to run test

**Comment by Extravi** [comment]
2captcha is very cheap but it adds up overtime so I need to make it harder to detect and block so it uses the API less

**Comment by Extravi** [comment]
once the first recaptca pops up it's going to pop up more often I noticed so I need to find ways to make the request system seem like a real user

**Comment by Extravi** [comment]
I did notice that a headless chrome browser doesn't really use that much memory and there are undetected versions of it so that could become a scraping option in the config at some point

**Comment by Extravi** [comment]
nvm that might not be practical

**Comment by Extravi** [comment]
odd i cant seem to get the "_GRECAPTCHA" cookie

**Comment by Extravi** [comment]
oh in chrome based browsers its not stored under cookies its stored under local storage

**Comment by Extravi** [comment]
> oh in chrome based browsers its not stored under cookies its stored under local storage

odd i cant get it atm 
![image](https://github.com/Extravi/araa-search/assets/98912029/5207a589-36f1-4436-a45d-3a7350939b0c)

**Comment by Extravi** [comment]
> Does 2captcha also work for self hosted instances without the hoster having to pay?

no but if you want to help test i can send you come credits

**Comment by Extravi** [comment]
> Does 2captcha also work for self hosted instances without the hoster having to pay?

![image](https://github.com/Extravi/araa-search/assets/98912029/74f9711d-c23d-4f71-8803-daf4aba51681)

**Comment by Extravi** [comment]
if you make an account email be the email you used and i can send some credit that could help

**Comment by Extravi** [comment]
some cookies used by google are region based so in the UK you won't get everything i can get testing in NA

**Comment by Extravi** [comment]
but "_GRECAPTCHA" is in the EU, UK and NA

**Comment by Extravi** [comment]
i also do my test using high load free vpn servers to make sure it has a recaptcha i send a request in a private window using "https://www.google.com/search?q=google"
![image](https://github.com/Extravi/araa-search/assets/98912029/00749c89-1259-4f24-82ea-d763b9a68d6d)

**Comment by amogusussy** [comment]
I think there should be an option in the config file for if you want to use a captcha solver then.
Maybe have something like #106 (the PR isn't that great, so I might redo it) for if the admin chooses not to use a captcha solver.
Having to pay will probably turn most people away from self hosting.

**Comment by Extravi** [comment]
its already an option in the config

**Comment by Extravi** [comment]
its turned off by default but i have it on for testing 

![image](https://github.com/Extravi/araa-search/assets/98912029/cf809ac9-ab3d-4d33-906d-197b7d2c12e9)

**Comment by Extravi** [comment]
i have done a total of 182 captchas in my test and only used 0.54 cents 
![image](https://github.com/Extravi/araa-search/assets/98912029/09572b32-bdc4-4dcf-88b4-0d530ac544c7)

**Comment by Extravi** [comment]
> i have done a total of 182 captchas in my test and only used 0.54 cents ![image](https://private-user-images.githubusercontent.com/98912029/294068896-09572b32-bdc4-4dcf-88b4-0d530ac544c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzQ1MDMsIm5iZiI6MTcwNDMzNDIwMywicGF0aCI6Ii85ODkxMjAyOS8yOTQwNjg4OTYtMDk1NzJiMzItYmRjNC00ZGNmLTg4YjQtMGQ1MzBhYzU0NGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyMTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDUyZWRmNDFmMTVlYzQ3NzQ1OGExY2Y5ODZhYzVhMTM1YTFiNjAxZjNiODZjYWVkOTZiZGQ2N2YxZjMwNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9w0EJFTBZSO4RG3qnK-eItwJS7FasaQlBUVqtaDB520)


most of this is from debugging the code on a instance it will use the api far less

**Comment by amogusussy** [comment]
Do you think an alternative search engine would be good for people who chose not to have it though? Some people might just not want to give their credit card info to them.
Also, how accurate is it? Does it usually work on the first attempt at solving, or does it take several? I know a lot of sites are now using AI generated captchas, which might cause issues for if google starts using a different captcha.

**Comment by Extravi** [comment]
It does it in its first attempt out of the 182 sent; it got one wrong for the server to do everything with it and the web driver; it totals 43.99 seconds.
![image](https://github.com/Extravi/araa-search/assets/98912029/381d30d4-b9f6-4fc6-948f-b70cf670c67c)

**Comment by Extravi** [comment]
results will look something like this in the file 
![image](https://github.com/Extravi/araa-search/assets/98912029/e379766e-06ff-405f-b37a-bfb6e44a67c7)

**Comment by Extravi** [comment]
> Here's a few changes I'd add:
> 
> ```
> from urllib.parse import urlparse
> 
> 
> # Force all requests to only use IPv4
> requests.packages.urllib3.util.connection.HAS_IPV6 = False
> 
> def makeHTMLRequest(url: str, is_google=False):
>     # block unwanted request from an edited cookie
>     domain = urlparse(url).netloc
>     if domain not in WHITELISTED_DOMAINS:
>         raise Exception(f"The domain '{domain}' is not whitelisted.")
> 
>     if is_google:
>         # get google cookies
>         with open("./2captcha.json", "r") as file:
>             data = json.load(file)
>         cookies = {
>             "OGPC": data["GOOGLE_OGPC_COOKIE"],
>             "NID": data["GOOGLE_NID_COOKIE"],
>             "AEC": data["GOOGLE_AEC_COOKIE"],
>             "1P_JAR": data["GOOGLE_1P_JAR_COOKIE"],
>             "GOOGLE_ABUSE_EXEMPTION": data["GOOGLE_ABUSE_COOKIE"]
>         }
>     else:
>         cookies = {}
> 
>     headers = {
>         "User-Agent": random.choice(user_agents),  # Choose a user-agent at random
>         "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
>         "Accept-Encoding": "gzip, deflate",
>         "Accept-Language": "en-US,en;q=0.5",
>         "Dnt": "1",
>         "Sec-Fetch-Dest": "document",
>         "Sec-Fetch-Mode": "navigate",
>         "Sec-Fetch-Site": "none",
>         "Sec-Fetch-User": "?1",
>         "Upgrade-Insecure-Requests": "1"
>     }
> 
>     # Grab HTML content with the specific cookie
>     html = requests.get(url, headers=headers, cookies=cookies)
> 
>     # Return the BeautifulSoup object
>     return BeautifulSoup(html.text, "lxml")
> ```
> 
> This sets `requests.packages.urllib3.util.connection.HAS_IPV6` before the function, because it only needs to be set once. Uses urlparse rather than splitting strings. Only uses the cookies if the the function is called as makeHTMLRequest(url, is_google=True), so other requests don't send unnecessary cookies, and don't waste time parsing the file. And removes a few one time use variables because they don't need to be variables.

where would i set is_google=?

**Comment by Extravi** [comment]
> Do you think an alternative search engine would be good for people who chose not to have it though? Some people might just not want to give their credit card info to them. Also, how accurate is it? Does it usually work on the first attempt at solving, or does it take several? I know a lot of sites are now using AI generated captchas, which might cause issues for if google starts using a different captcha.

Googles recaptcha also uses ai btw

**Comment by Extravi** [comment]
> Here's a few changes I'd add:
> 
> ```
> from urllib.parse import urlparse
> 
> 
> # Force all requests to only use IPv4
> requests.packages.urllib3.util.connection.HAS_IPV6 = False
> 
> def makeHTMLRequest(url: str, is_google=False):
>     # block unwanted request from an edited cookie
>     domain = urlparse(url).netloc
>     if domain not in WHITELISTED_DOMAINS:
>         raise Exception(f"The domain '{domain}' is not whitelisted.")
> 
>     if is_google:
>         # get google cookies
>         with open("./2captcha.json", "r") as file:
>             data = json.load(file)
>         cookies = {
>             "OGPC": data["GOOGLE_OGPC_COOKIE"],
>             "NID": data["GOOGLE_NID_COOKIE"],
>             "AEC": data["GOOGLE_AEC_COOKIE"],
>             "1P_JAR": data["GOOGLE_1P_JAR_COOKIE"],
>             "GOOGLE_ABUSE_EXEMPTION": data["GOOGLE_ABUSE_COOKIE"]
>         }
>     else:
>         cookies = {}
> 
>     headers = {
>         "User-Agent": random.choice(user_agents),  # Choose a user-agent at random
>         "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
>         "Accept-Encoding": "gzip, deflate",
>         "Accept-Language": "en-US,en;q=0.5",
>         "Dnt": "1",
>         "Sec-Fetch-Dest": "document",
>         "Sec-Fetch-Mode": "navigate",
>         "Sec-Fetch-Site": "none",
>         "Sec-Fetch-User": "?1",
>         "Upgrade-Insecure-Requests": "1"
>     }
> 
>     # Grab HTML content with the specific cookie
>     html = requests.get(url, headers=headers, cookies=cookies)
> 
>     # Return the BeautifulSoup object
>     return BeautifulSoup(html.text, "lxml")
> ```
> 
> This sets `requests.packages.urllib3.util.connection.HAS_IPV6` before the function, because it only needs to be set once. Uses urlparse rather than splitting strings. Only uses the cookies if the the function is called as makeHTMLRequest(url, is_google=True), so other requests don't send unnecessary cookies, and don't waste time parsing the file. And removes a few one time use variables because they don't need to be variables.

It's been added
```python
from urllib.parse import unquote, urlparse

# Force all requests to only use IPv4
requests.packages.urllib3.util.connection.HAS_IPV6 = False

def makeHTMLRequest(url: str, is_google=False):
    # block unwanted request from an edited cookie
    domain = unquote(url).split('/')[2]
    if domain not in WHITELISTED_DOMAINS:
        raise Exception(f"The domain '{domain}' is not whitelisted.")

    if is_google:
        # get google cookies
        data = load_config()
        cookies = {
            "OGPC": data["GOOGLE_OGPC_COOKIE"],
            "NID": data["GOOGLE_NID_COOKIE"],
            "AEC": data["GOOGLE_AEC_COOKIE"],
            "1P_JAR": data["GOOGLE_1P_JAR_COOKIE"],
            "GOOGLE_ABUSE_EXEMPTION": data["GOOGLE_ABUSE_COOKIE"]
        }
    else:
        cookies = {}

    headers = {
        "User-Agent": random.choice(user_agents),  # Choose a user-agent at random
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-US,en;q=0.5",
        "Dnt": "1",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "none",
        "Sec-Fetch-User": "?1",
        "Upgrade-Insecure-Requests": "1"
    }
    
    # Grab HTML content with the specific cookie
    html = requests.get(url, headers=headers, cookies=cookies)

    # Return the BeautifulSoup object
    return BeautifulSoup(html.text, "lxml")

**Comment by Extravi** [comment]
> alternative search engine

an alternative search engine is not a bad idea and i will be looking into that soon but i want to finish how request are made first

**Comment by Extravi** [comment]
im going to add support to proxy google autocomplete as a setting because its faster then duckduckgos 
![image](https://github.com/Extravi/araa-search/assets/98912029/893c1358-6b98-4dd6-9b9b-4efaea141905)

**Comment by Extravi** [comment]
Each domain will now have its own persistent session, so I won't need to establish a new https/tls connection for each domain, and I can take advantage of connection reuse. This should greatly improve speeds. Also, each session will be isolated and have its own cookies, etc., making everything more reliable.

**Comment by Extravi** [comment]
Video demo of what's possible with persistent sessions and connection reuse. Persistence sessions have already been added to my instance, but I cannot take advantage of connection reuse unless I set up a persistent session for each domain, and that's something I am currently working on.
https://github.com/Extravi/araa-search/assets/98912029/96a7d011-9efe-4e03-9120-578760f97b77

**Comment by Extravi** [comment]
> ![image](https://private-user-images.githubusercontent.com/98912029/294122714-fcb8a69b-11ec-4d49-bdff-9e908cbf96c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTY1NTIsIm5iZiI6MTcwNDM1NjI1MiwicGF0aCI6Ii85ODkxMjAyOS8yOTQxMjI3MTQtZmNiOGE2OWItMTFlYy00ZDQ5LWJkZmYtOWU5MDhjYmY5NmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA4MTczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NzY4NWYxZDU4MjY2ODE2Zjk4N2IwZjY2OTg0MzBmMWFlMmRjNzQyMzY0MDAwOGM2NmE2NmNmNjk4MWE1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZfSPKaXLTvHLy3mfcVtnvGfQspkK7lpVgwwN4htVp-Y)

i will need to check each request and they will each need their own persistent session and each session is in memory/ram so its quite fast

**Comment by Extravi** [comment]
ill add it tmr with some other stuff

**Comment by Extravi** [comment]
@amogusussy @TEMtheLEM 
![image](https://github.com/Extravi/araa-search/assets/98912029/14127722-bcce-40fd-aae6-f442e2daa5b9)

**Comment by Extravi** [comment]
This change should add more redundancy and make everything faster and more reliable.

**Comment by Extravi** [comment]
the first request will look something like this 
![image](https://github.com/Extravi/araa-search/assets/98912029/0955759a-9b8a-4474-a59b-b66c537c6b27)
any request after will look like this
![image](https://github.com/Extravi/araa-search/assets/98912029/dab13c37-fa57-43cf-a68f-404b3c4813e9)

**Comment by Extravi** [comment]
Now there is no need to start a new request every time, saving on request response time and making everything faster.

**Comment by Extravi** [comment]
image at first request
![image](https://github.com/Extravi/araa-search/assets/98912029/ac5b2385-25b9-492d-822f-e6d20d9c9d0b)
![image](https://github.com/Extravi/araa-search/assets/98912029/6885906f-145c-45e0-a315-1360d846a28e)
any request after
![image](https://github.com/Extravi/araa-search/assets/98912029/5849f6ca-2525-4491-9530-7b30f41343e7)
![image](https://github.com/Extravi/araa-search/assets/98912029/099fed84-4eea-4a69-97f0-43bb634f0318)

**Comment by Extravi** [comment]
If you have any ideas on how I can further make the request better or faster, let me know.
