### ISSUE TITLE
Docker domain env

### ISSUE THREAD

**Issue by rafalohaki** [Extravi/araa-search#109]
i did uncommented 
#DOMAIN=
to 
DOMAIN=example.wpwdw.com

but i get error after running a container
```
Make a DOMAIN env. variable & set it to your domain!
    (Ex; DOMAIN=www.yourdomain.com)
```
changed name of opensearch.xml too

**Comment by TEMtheLEM** [comment]
Are you using Docker compose, or are you running the container manually?

**Comment by rafalohaki** [comment]
im building it from 
```
docker build -t araasearch .```
then running a container of this image

**Comment by TEMtheLEM** [comment]
If you're running the container by doing `docker run`, be sure to pass the argument `--env-file /path/to/.env` and expose the port by doing `-p <enter port here>:<enter port here>`.

**Comment by TEMtheLEM** [comment]
An example; `docker run --env-file ./.env -p 8000:8000 araa-search`

**Comment by rafalohaki** [comment]
thanks, its working:
https://search.wpme.pl/

**Comment by amogusussy** [comment]
@Extravi Can you update the README.md file?
