### ISSUE TITLE
image search does not work with post request

### ISSUE THREAD

**Issue by Extravi** [Extravi/araa-search#112]
![image](https://github.com/Extravi/araa-search/assets/98912029/7d7145e5-b287-482e-9565-f438b48a7995)

**Comment by amogusussy** [comment]
Could change it to:
```
if (document.querySelectorAll(".search-active")[1].innerText === "Images") {
    // Do image search stuff
}
```
This checks which of the search buttons is selected. If it's images, then do whatever it says.

**Comment by Extravi** [comment]
alright ill test that and add it in the update with ui fixes

**Comment by Extravi** [comment]
thanks

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/04e28f39-c6df-40d6-a9db-7add95fc5f91)

**Comment by Extravi** [comment]
works thank you

**Comment by amogusussy** [comment]
Can you check that it works with other languages? Im not at my computer right now, so i cant.

It should probably be changed to use .value instead of .innerText, because .value stays the same across all ux languages.

**Comment by amogusussy** [comment]
Also,remove the 'All' and the index from the queryselector function to improve efficiency.

**Comment by Extravi** [comment]
> Can you check that it works with other languages? Im not at my computer right now, so i cant.
> 
> It should probably be changed to use .value instead of .innerText, because .value stays the same across all ux languages.

I already added it to the code but I'll go back and make that change

**Comment by Extravi** [comment]
> Can you check that it works with other languages? Im not at my computer right now, so i cant.
> 
> It should probably be changed to use .value instead of .innerText, because .value stays the same across all ux languages.

the value is there in all pages tho

**Comment by Extravi** [comment]
it dose not work without querySelectorAll but this version works

```javascript
if (document.querySelectorAll(".search-active")[1].getAttribute("value") === "image") {

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/5f2e0250-95c6-4154-afde-1043695c2b85)

**Comment by Extravi** [comment]
https://github.com/Extravi/araa-search/commit/f3ef65e2a26c8424a7ee6860c315ee9004c809eb
