### ISSUE TITLE
I am now hosting a YouTube privacy frontend, and the API may be used for video search to speed things up.

### ISSUE THREAD

**Issue by Extravi** [Extravi/araa-search#120]
https://yt.extravi.dev/trending
https://ytapi.extravi.dev/

I'm not sure how to use the API yet, but I'll find out.

**Comment by Extravi** [comment]
https://ytapi.extravi.dev/search?q=test&filter=all

**Comment by Extravi** [comment]
before using Invidious
![image](https://github.com/Extravi/araa-search/assets/98912029/d525f62c-7b53-4c46-a4ac-02b2f04a4840)
after using Piped
![image](https://github.com/Extravi/araa-search/assets/98912029/1686baa5-28b9-45ea-9f66-27f184f8ae18)

**Comment by Extravi** [comment]
ill format and fix views

**Comment by amogusussy** [comment]
What's the point of a video tab if all it does is give you youtube results? Wouldn't it just be better to just search it on youtube?
You could use something like brave, qwant, google, bing, etc. Then, we'd have results from across many different sites.

**Comment by Extravi** [comment]
https://github.com/Extravi/araa-search/commit/26e3be842935b11775671b08be8af7be2346560b

**Comment by Extravi** [comment]
> What's the point of a video tab if all it does is give you youtube results? Wouldn't it just be better to just search it on youtube? You could use something like brave, qwant, google, bing, etc. Then, we'd have results from across many different sites.

easy to maintain and less likely to get rate limited

**Comment by Extravi** [comment]
i did use brave video search before but they removed it for like a month breaking everything

**Comment by Extravi** [comment]
> What's the point of a video tab if all it does is give you youtube results? Wouldn't it just be better to just search it on youtube? You could use something like brave, qwant, google, bing, etc. Then, we'd have results from across many different sites.

also most people just use youtube i dont watch videos from other sites

**Comment by Extravi** [comment]
also startpage does the same thing and only shows youtube for video results

**Comment by Extravi** [comment]
im sure its fine

**Comment by Extravi** [comment]
@amogusussy let me know the speeds are for piped for you it should be quite fast because not many people are using and the network optimization done with nginx and cloudflare

**Comment by Extravi** [comment]
https://yt.extravi.dev/trending
