### ISSUE TITLE
URL and title mismatch

### ISSUE THREAD

**Issue by Extravi** [Extravi/araa-search#137]
```python
    # results
    result_divs = soup.findAll("div", {"class": "MjjYud"})
    
    # initialize lists to store data
    titles = []
    descriptions = []
    hrefs = []

    # loop through each div
    for div in result_divs:
        # retrieve links
        if not div.find("div", class_="cUnQKe"):
            link = div.find("a")
            if link is not None:
                hrefs.append(link.get("href"))
            
            # retrieve title
            title = div.find("h3")
            if title is not None:
                titles.append(title.text.strip())
            
            # retrieve description
            desc = div.find("div", {"class": "VwiC3b"})
            if desc is not None:
                descriptions.append(desc.text.strip())
            else:
                descriptions.append("No description available.")
```

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/3b5ce322-c5b0-4fc1-95eb-9a29e30d3bfd)
![image](https://github.com/Extravi/araa-search/assets/98912029/906644b3-5015-485f-b4a1-1698eea900bc)
https://araa.extravi.dev/search?q=chatgpt&t=text
https://araa.extravi.dev/search?q=telegram&t=text

**Comment by Extravi** [comment]
It does that for some results, but not all. I was trying to update the proxy to scrape from MjjYud so I could get more results like video urls, etc. from Google Search and later add the image base64 next to the results.
![image](https://github.com/Extravi/araa-search/assets/98912029/d04a754d-73c9-44fe-986a-f345c043adce)
![image](https://github.com/Extravi/araa-search/assets/98912029/f1d27c6e-dd0d-47b7-9ff2-8c973a8877ad)

**Comment by amogusussy** [comment]
You should probably just revert back to before these changes, then just do lots of testing before you push them again.
Right now, if I search something, I just get `Internal Server Error`.

**Comment by TEMtheLEM** [comment]
Please revert these changes from the `main` branch, and push them off to a seperate branch in the mean time until they are free of these bugs. You shouldn't just leave the project broken like this for an extended period of time.

**Comment by Extravi** [comment]
yeah i need to also idk how to fix this

**Comment by amogusussy** [comment]
Here's a solution that stops the mismatched links issue:
```
    # loop through each div
    for div in result_divs:
        # retrieve links
        if not div.find("div", class_="cUnQKe"):
            link = div.find("a")
            if link is not None:
                link = link.get("href")
            else:
                continue

            # retrieve title
            title = div.find("h3")
            if title is not None:
                title = title.text.strip()
            else:
                continue

            hrefs.append(link)
            titles.append(title)

            # retrieve description
            desc = div.find("div", {"class": "VwiC3b"})
            if desc is not None:
                descriptions.append(desc.text.strip())
            else:
                descriptions.append("No description available.")
```

This only appends the link and title if neither are empty.

The issue is caused by there being no else case for if the title or link is empty.
So the title may be there, and so it gets appended, but the link isn't, so that doesn't get appended.


However, this doesn't fix some other issues, like when it doesn't return any results. For example, if I search 'macbeth', only the wikipedia snippet is shown, which shows that there are results, but the current scraper isn't picking them up.

**Comment by amogusussy** [comment]
Also, this doesn't solve the issue where some links just say 'Images'.

**Comment by Extravi** [comment]
i went back to the older version for now 

https://github.com/Extravi/araa-search/commit/aa961298d15223a66ca75c4cc58e9e676702b19d
