### ISSUE TITLE
yt.extravi.dev doesn't show videos

### ISSUE THREAD

**Issue by amogusussy** [Extravi/araa-search#142]
If you click on any video in the videos tab, it takes you to yt.extravi.dev.
This doesn't show any video, and instead returns `Got error: "Sign in to confirm that you're not a bot"` no matter which video you open.

**Comment by Extravi** [comment]
blocked by google even tho the codes up to date

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/53ebac31-4dc4-4bda-aed0-5086a571fe10)

**Comment by Extravi** [comment]
just found out a test google is doing to some users now

**Comment by Extravi** [comment]
https://www.youtube.com/watch?v=9JYFMMNYz60

**Comment by Extravi** [comment]
https://github.com/TeamPiped/Piped/issues/3658
