### ISSUE TITLE
Wrong results with an specific query in main instance.

### ISSUE THREAD

**Issue by patyarishimai** [Extravi/araa-search#152]
I have found, randomly, that inputting the query [truly reset tcp ip], in the main instance, outputs way different results than those of google.com or any other instance of Araa. It happened as well when I look for isbn of books alongside with a topic of said box e.g. [neuroscience of habit isbn]. 

I think the way the main instance is scraping results from google has an issue. Hope it gets fixed soon!

**Comment by Extravi** [comment]
in cases where Google has temporarily blocked Araa with a captcha it will silently fallback on Qwant to prevent any downtime

**Comment by Extravi** [comment]
it does that for at least 28 minutes before trying again
