### ISSUE TITLE
app keeps refreshing on load

### ISSUE THREAD

**Issue by athiosh** [Extravi/araa-search#154]
First time deploying with docker, the app deployed fine but when opening the home page it just keep refreshing and won't allow me to search or do anything. When inspecting the page, I can see the error in screenshot

<img width="891" alt="Screenshot 2024-07-10 at 10 00 33 PM" src="https://github.com/Extravi/araa-search/assets/66545547/a35abf0e-bc44-4490-b795-2014ee44609a">

**Comment by Extravi** [comment]
it's because you need a secure HTTPS connection Araa automatically tries to set the language cookie

**Comment by fatez** [comment]
can it be used without an https domain?
I would like to install it on my machine locally and use it directly locally

thanks

**Comment by Extravi** [comment]
you would have to edit the code to disable it from setting a secure cookie

**Comment by Obamium69** [comment]
@athiosh Would you mind sharing the docker image? :)

**Comment by athiosh** [comment]
I added the code and its the same thing. I am hosting my docker on debian and its english based.

**Comment by amogusussy** [comment]
See if changing it to requests works:

    html = requests.get(url, headers=headers, verify=False) # persistent session for piped

**Comment by athiosh** [comment]
that worked, I had to also add "verify=False" to  /app/__init__.py img_proxy() function to get the image render correctly. It would be great if this can be enabled with environment variable in the future releases. Thank you

```bash
    elif url.startswith(f"https://{PIPED_INSTANCE_PROXY}"):
        response = requests.get(url, headers=headers, verify=False)
```
