### ISSUE TITLE
Display Favicons From Search Results

### ISSUE THREAD

**Issue by royaltongue** [Extravi/araa-search#157]
Would it be possible to allow for fetching/displaying favicons on the search result pages?

**Comment by Extravi** [comment]
this is something I thought about but I don't think it can be done in a reliable way and fast

**Comment by royaltongue** [comment]
[Whoogle Search](https://github.com/benbusby/whoogle-search) has the option on by default, and can be set using `WHOOGLE_SHOW_FAVICONS`
