### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DavidVeevt** [Extravi/araa-search#20]
Hi, I have a feature request for Tailsx. Is there anyway that you develop so that it has an AI chat function that uses gpt-3.5-turbo. Also is there any possibility to make the design similar to you.com or bing.com? 
AI Inspiration: You.com Chat and Bing Chat.
Design Inspiration: You.com, Bing.com and Neeva.com

**Comment by Extravi** [comment]
i am looking into adding chatgpt soon

**Comment by Extravi** [comment]
I don't have a working API key for openai and it cost money so I can't develop it sorry.

**Comment by Extravi** [comment]
![Screenshot from 2023-07-07 16 02 17](https://github.com/Extravi/tailsx/assets/98912029/ebafe2f0-a211-44c5-b4f7-f111fc459463)

**Comment by amogusussy** [comment]
You can use brave's summarizer.
This is the URL for its api:
`https://search.brave.com/api/summarizer?key=query:us:en`

It's quite good, since it gives references to what it's saying, and if it knows something's wrong, it wont give any result.

Also, its terms of use seem okay too. This is all I could find that could be somewhat related to API use, but Tailsx doesn't have a lot of users, so its load wont be 'unreasonable.'

```
Further, you shall not (directly or indirectly): 
(i) take any action that imposes or may impose an unreasonable or disproportionately large load on Brave’s (or its third party providers’) infrastructure; or
(ii) interfere or attempt to interfere with the proper working of the Service or any activities conducted on the Service; 
(iii) bypass any measures Brave may use to prevent or restrict access to the Service (or parts thereof).
```

**Comment by Extravi** [comment]
> You can use brave's summarizer. This is the URL for its api: `https://search.brave.com/api/summarizer?key=query:us:en`
> 
> It's quite good, since it gives references to what it's saying, and if it knows something's wrong, it wont give any result.
> 
> Also, its terms of use seem okay too. This is all I could find that could be somewhat related to API use, but Tailsx doesn't have a lot of users, so its load wont be 'unreasonable.'
> 
> ```
> Further, you shall not (directly or indirectly): 
> (i) take any action that imposes or may impose an unreasonable or disproportionately large load on Brave’s (or its third party providers’) infrastructure; or
> (ii) interfere or attempt to interfere with the proper working of the Service or any activities conducted on the Service; 
> (iii) bypass any measures Brave may use to prevent or restrict access to the Service (or parts thereof).
> ```

i will use this instead

**Comment by amogusussy** [comment]
The requests can take a lot of time though, so it's probably best to implement it as a javascript fetch, rather than preloaded on every page.

**Comment by Extravi** [comment]
do you have revolt.chat something amogusussy

**Comment by amogusussy** [comment]
I don't right now, but I can make one tomorrow (I'm about to go to sleep) if you want.

**Comment by Extravi** [comment]
i made a key but i dont know how to use it https://search.brave.com/api/summarizer?key=mykey&query=firefox

**Comment by Extravi** [comment]
```json
{"type":"summarizer","status":"failed","results":[]}
```

**Comment by TEMtheLEM** [comment]
@Extravi try setting `key` to the search query

**Comment by amogusussy** [comment]
It only allows certain types of queries.

Try searching "what is the periodic table". That query gives a response for me.

**Comment by amogusussy** [comment]
Also, I don't think you need a key. Not including a key would make self hosting a lot easier.

**Comment by Extravi** [comment]
https://search.brave.com/api/summarizer?key=what%20is%20the%20periodic%20table:us:en

```json
{"type":"summarizer","status":"failed","results":[]}
```

**Comment by amogusussy** [comment]
Try setting the user agent header.

Also, you could try searching it normally in search.brave.com, and see if any box that says summariser shows up. It might only be allowed in certain countries, due to new ai regulations.

**Comment by Extravi** [comment]
I think I will scrap this idea. The API isn't reliable when I could focus on other things.

**Comment by Extravi** [comment]
It works sometimes and sometimes it won't.

**Comment by Extravi** [comment]
I am not sure about it because how they get the API keys does not seem right and could be breaking OpenAI's TOS.

**Comment by Extravi** [comment]
like i dont want to get this project taken down by openai

**Comment by Extravi** [comment]
so i likely wont be using that

**Comment by Extravi** [comment]
i might use something else

**Comment by Extravi** [comment]
it's something that will happen at some point

**Comment by Extravi** [comment]
I'm working on adding asynchronous support using httpx first
