### ISSUE TITLE
plans to translate TailsX into more than one language

### ISSUE THREAD

**Issue by Extravi** [Extravi/araa-search#52]
I will be translating TailsX into more than one language over time. I will also provide documentation in more than one language to hopefully grow the project, among other things.

English:
![image](https://github.com/Extravi/tailsx/assets/98912029/012d996b-78ea-4a4a-a265-f24e49495a4d)
French:
![image](https://github.com/Extravi/tailsx/assets/98912029/8a4afc33-64d2-4093-85b0-7b7a7f33bac7)
English:
![image](https://github.com/Extravi/tailsx/assets/98912029/d1077afd-2a75-4e16-a431-d56a00f875fd)
French:
![image](https://github.com/Extravi/tailsx/assets/98912029/3ab68e5e-eb08-4991-b8cb-0e8aa464c436)

**Comment by amogusussy** [comment]
Do you have any plans on how to implement this yet, or is it just a concept?

**Comment by Extravi** [comment]
yes a JSON file with every supported language it in and a cookie so the browser knows what language to use

**Comment by Extravi** [comment]
the JSON file would have the translation for each language

**Comment by amogusussy** [comment]
Cool. Do you know how roughly how much text needs to be translated?

**Comment by Extravi** [comment]
yes

**Comment by Extravi** [comment]
updated helpers.py https://github.com/Extravi/tailsx/commit/d7d9f8b46cb1b0f1624d8800dfee6a535fe41969

**Comment by Extravi** [comment]
that fixes support for asian languages

**Comment by Extravi** [comment]
before:
![image](https://github.com/Extravi/tailsx/assets/98912029/56f439ec-de5f-4668-8589-5a21f38a2fd8)
after the fix:
![image](https://github.com/Extravi/tailsx/assets/98912029/8ebee870-b112-48e5-8d86-4cc9eeba5af6)


https://tailsx.extravi.dev/search?q=%E6%9D%B1%E4%BA%AC%E8%A6%B3&t=text

**Comment by Extravi** [comment]
before i start translating the user interface i need to make sure everything works correctly

**Comment by Extravi** [comment]
also settings on mobile etc has been improved 
before:
![image](https://github.com/Extravi/tailsx/assets/98912029/96356bb9-3bc6-4ba9-a1da-f3f4938c8735)
after: 
![image](https://github.com/Extravi/tailsx/assets/98912029/5f067449-a317-4e29-a90d-8fb71b800e12)

**Comment by Extravi** [comment]
> updated helpers.py [d7d9f8b](https://github.com/Extravi/tailsx/commit/d7d9f8b46cb1b0f1624d8800dfee6a535fe41969)

nvm i need to revert this

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/441b4830-6bb4-4e69-8f00-885be4969db5)
![image](https://github.com/Extravi/araa-search/assets/98912029/30c087e6-f1ae-4400-a1ea-441c426f1288)
![image](https://github.com/Extravi/araa-search/assets/98912029/f0c41bbf-8667-4e8a-922e-8fe6385cd7e5)

**Comment by Extravi** [comment]
i will have more soon once i push the update

**Comment by Extravi** [comment]
i also want to add something to detect the language the user is using

**Comment by Extravi** [comment]
its not prefect but it will be improved on overtime but the framework for it is now there 
https://github.com/Extravi/araa-search/assets/98912029/97f17643-8c13-4395-82f4-a65cf6881fd4

**Comment by Extravi** [comment]
https://github.com/Extravi/araa-search/commit/621d16601ff32f073c7a8197c86e88d5d5f1ce93
https://github.com/Extravi/araa-search/commit/54d5f561256a3c8598c4676901a6d7b0de3bd816
