### ISSUE TITLE
Requests blocked by google

### ISSUE THREAD

**Issue by unstablemaple** [Extravi/araa-search#60]
![image](https://github.com/Extravi/tailsx/assets/145098674/873cd6f9-0633-4b40-a598-e43e43140b94)
As you can see in the image above, text results return nothing, I tried `curl https://google.com` and it gave me a `403 Forbidden` Any workaround for this?

**Comment by Extravi** [comment]
are you running your own instance?

**Comment by Extravi** [comment]
what vps provider if you are

**Comment by unstablemaple** [comment]
@Extravi, yes, it's my own instance hosted on a Hetzner VPS.

**Comment by Extravi** [comment]
do you have IPv6 enabled?

**Comment by unstablemaple** [comment]
No

**Comment by Extravi** [comment]
did you follow the guide and disable ipv6

**Comment by unstablemaple** [comment]
I have IPv6 disabled, yes.

**Comment by Extravi** [comment]
you need to disable ipv6 google is more likely to block it

**Comment by unstablemaple** [comment]
@Extravi I have it disabled already.

**Comment by Extravi** [comment]
https://extravi.dev/tailsx/

**Comment by Extravi** [comment]
did you do this 

bash -c 'cat <> /etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF'

**Comment by Extravi** [comment]
once you have down that restart the vps

**Comment by Extravi** [comment]
also what distro are you using

**Comment by unstablemaple** [comment]
I checked that I have IPv6 disabled, rebooted then tried again, and it's still not working. I am running Debian 12 and TailsX inside Docker.

**Comment by Extravi** [comment]
try to curl google search with a user agent

**Comment by unstablemaple** [comment]
I curled google and it worked after the reboot, however same deal with TailsX.

**Comment by Extravi** [comment]
are you using a fork or did you edit the code?

**Comment by unstablemaple** [comment]
I just cloned the repo and ran it in docker.

**Comment by Extravi** [comment]
you could try it without docker i dont know much about docker

**Comment by taskylizard** [comment]
Any reason why disabling IPv6 is a requirement? I'm also running my own instance and the frequent blocker is requests being blocked, while the popular alternatives, [whoogle-search](https://github.com/benbusby/whoogle-search) and LibreX (which this project is based on, it seems) do not have such requirements and can function totally fine.

**Comment by Extravi** [comment]
google blocks ipv6 addresses more likely

**Comment by Extravi** [comment]
librex only sends request in ipv4

**Comment by Extravi** [comment]
this is not based on librex

**Comment by Extravi** [comment]
@taskylizard TailsX is not based on LibreX; it is not even close. The only thing that looks kind of close is the user interface, but thats because I made the user interface for LibreX.

This is the LibreX code base.
![image](https://github.com/Extravi/tailsx/assets/98912029/55af2ee7-2ca6-4dd5-9427-e1721c21787a)

vs TailsX
![image](https://github.com/Extravi/tailsx/assets/98912029/4a4f71f9-ce82-4ca4-b35e-7a48c2383494)

**Comment by Extravi** [comment]
this is how tailsx does request:
https://github.com/Extravi/tailsx/blob/ec92c830d9b776296815e556bd2883c45e19b54b/_config.py#L21C1-L21C1
https://github.com/Extravi/tailsx/blob/ec92c830d9b776296815e556bd2883c45e19b54b/src/helpers.py#L11

**Comment by Extravi** [comment]
TailsX also has more security measures than LibreX, and TailsX is also more consistent.

**Comment by Extravi** [comment]
TailsX
![Screenshot 2023-09-26 141533](https://github.com/Extravi/tailsx/assets/98912029/e184ff89-0e5b-4694-be74-c827d1267d9b)

LibreY because I can't find one working LibreX instance. 
![image](https://github.com/Extravi/tailsx/assets/98912029/a2ca7b83-7d5d-4e8d-bd2d-74a49bdf7859)

**Comment by Extravi** [comment]
I started TailsX to solve all the problems and disagreements I have with LibreX.

**Comment by Extravi** [comment]
That's why TailsX is not based on LibreX. LibreX uses PHP, and TailsX uses Python with Flask.

**Comment by NormTurtle** [comment]
@taskylizard literally triggered the dude so high :|

**Comment by unstablemaple** [comment]
I feel like this conversation derailed from the main issue. @Extravi, do you have Matrix? I'd prefer to continue this conversation elsewhere.

**Comment by Extravi** [comment]
i have telegram

**Comment by Extravi** [comment]
and email

**Comment by Extravi** [comment]
extravi@extravi.dev
