### ISSUE TITLE
Rename TailsX to Aura/Aura Search?

### ISSUE THREAD

**Issue by Extravi** [Extravi/araa-search#67]
![Screenshot from 2023-10-07 14-36-53](https://github.com/Extravi/tailsx/assets/98912029/7b7b4622-036d-4d6e-ab8c-c1f372652acf)
@TEMtheLEM @amogusussy

**Comment by Extravi** [comment]
Why? I don't want to be confused with TailsOS, among other things, because of the name TailsX.

**Comment by amogusussy** [comment]
Is there any significance behind the name?
Also, I like the different color ending letter in 'Libre**X**', and 'Tails**X**'.

**Comment by unstablemaple** [comment]
I also liked the colored uppercase letter, you could color the 'A' in Aura. I believe AuraSearch is too long. I think AuraX with a colored X would be nice. Unless you still haven't decided on having 'Aura' in the name I could brainstorm other names.
![image](https://github.com/Extravi/aura-search/assets/145098674/fd5970ee-0c12-472e-803d-2ec72f6e770d)
![image](https://github.com/Extravi/aura-search/assets/145098674/bf4132d8-bbe7-4c53-b6c0-27566f7c2fdd)

You could also use the X to add small magnifying glass like this rushed sketch I made with my screenshot app.

![image](https://github.com/Extravi/aura-search/assets/145098674/4c8ac7d2-4a96-4a1a-8b2c-7b87781c2b9d)
![image](https://github.com/Extravi/aura-search/assets/145098674/af18555f-7c99-4dc5-9628-6dec13350597)

Dimensions of the glass are obviously to be changed, it's just an illustration of what I have in mind.

**Comment by unstablemaple** [comment]
Or you could have a colored "X" and have it inside a magnifying glass, which makes it "uppercase"

**Comment by Extravi** [comment]
> AuraSearch

I was not going to use AuraSearch I am just using Aura
![image](https://github.com/Extravi/aura-search/assets/98912029/8ea25e6b-4eef-400b-881f-873238e9a0fa)

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/aura-search/assets/98912029/e9429669-b600-4cc5-bd4d-07e874d3a32b)

**Comment by Extravi** [comment]
idk i just came up with this name now i kinda want to name it this does it sound better then Aura

**Comment by Extravi** [comment]
idk i think it looks better then Aura

**Comment by Extravi** [comment]
it also just reads better to me

**Comment by Extravi** [comment]
that is still something i want to do but legally

**Comment by Extravi** [comment]
i cant use thos openai apis from discord for reasons

**Comment by Extravi** [comment]
i need a free api to do it

**Comment by Extravi** [comment]
i went with Araa but i still need to fix things many things in the repo and others are still named TailsX like docker idk i dont have time to fix it atm i have not slept all night lol its 6 am

**Comment by amogusussy** [comment]
If you want to keep it called aura, you could call it `Aura+`, and have the `+` highlighted.

**Comment by unstablemaple** [comment]
Using cloudflare is a really bad idea, especially on services like Aura/Tailsx/Araa, it literally defeats the whole purpose of such services. We use and host instances so we can proxy our traffic through the hosted instance so Google/DDG won't be able to fingerprint us with their algorithms and collect our searches. Effectively, what you are doing is giving your searches your data to Cloudflare (which probably sells back to Google) instead of giving it directly to Google. The CDN decrypts the content of your request so it can deliver it.

>    SSL is terminated at the Cloudflare edge server. Then it is encrypted again and sent back to your servers all encrypted. You need an SSL certificate installed directly on your server. Also, you may use a self-signed certificate.   When you use Cloudflare, we must decrypt the data at our edge in order to cache and filter any bad traffic.

Aside from that, they have fingerprinting methods when you try and access any of their (sub-)domains. Install [JShelter](https://jshelter.org/) to see the fingerprinting in action.

**Comment by SillyBilly10** [comment]
it reminds me of Arai

**Comment by SillyBilly10** [comment]
Wait, what if you could just customize the text to be whatever you want? That would be pretty funny
