### ISSUE TITLE
Plans to add other search engines.

### ISSUE THREAD

**Issue by amogusussy** [Extravi/araa-search#68]
I'm planning on implementing other search engines (qwant, ddg, startpage, and maybe some others). There'll be an option in the settings to set your preferred engine.
This will most likely mean a rewrite of textResults.py, and results.html, to make them both more readable, and easier to develop, so I'm announcing that I'm going to do it so that potential merge conflicts can be avoided.
If there's any other engines I should implement, or any potential conflicts with other work that someone else is doing on the project, please tell me.
I plan to start this tomorrow.

**Comment by Extravi** [comment]
There don't

**Comment by Extravi** [comment]
Pleases don't

**Comment by Extravi** [comment]
I have been planning and working on my own index for some time now, and there will be conflicts as a result of that.

**Comment by Extravi** [comment]
I started this back in May https://github.com/Extravi/search-index

**Comment by Extravi** [comment]
I have been working on this privately since

**Comment by Extravi** [comment]
I will soon have partially independent results using a mix of Google's and mine.

**Comment by amogusussy** [comment]
> I started this back in May https://github.com/Extravi/search-index

I dont plan to make an indexer, just an option to use different search engines.

**Comment by Extravi** [comment]
yeah but it won't integrate well with my index

**Comment by Extravi** [comment]
i don't want more to work with in the future

**Comment by Extravi** [comment]
when i add my index

**Comment by amogusussy** [comment]
Do you have an estimate for how long it will be until you add your indexer?

**Comment by Extravi** [comment]
its going to take some time but likely news and wikipedia and youtube will come first and mixed in with the google results

**Comment by Extravi** [comment]
so i can add images and more visuals into the results

**Comment by Extravi** [comment]
i cant add any other engines for the time being until this is done no eta

**Comment by Extravi** [comment]
this will likely make "Aura Search" the first open source search engine with its own index

**Comment by Extravi** [comment]
Being on par with closed-source software has been a goal since I started this project almost a year ago.

**Comment by Extravi** [comment]
So that means both the user interface and what it does in the backend.

**Comment by Extravi** [comment]
Some projects, like LibreX, assume the user knows what they are doing, so they won't try to simplify things, and others, like SearX and SearXNG, have a cluttered interface. I want to simplify things and keep things clean on the user end for my project so anyone can use it.

**Comment by Extravi** [comment]
I want to keep my project as simple and accessible as possible.

**Comment by Extravi** [comment]
Before I worked on LibreX's interface, it looked like this: 
![image](https://github.com/Extravi/tailsx/assets/98912029/dd7b8ccf-cb41-4954-a217-791336497432)
I am the person who cleaned it up, mostly until I stopped working on it. That's why LibreX kind of looks like soon to be "Aura Search".

**Comment by Extravi** [comment]
https://github.com/hnhx/librex/pull/41 https://github.com/hnhx/librex/pull/49

**Comment by Extravi** [comment]
there is much more then that 
![image](https://github.com/Extravi/tailsx/assets/98912029/1988f5e4-37c2-4224-be22-455d79bfa07a)

**Comment by Extravi** [comment]
like the html for it to like the logo in text off to the left i did that 
![image](https://github.com/Extravi/tailsx/assets/98912029/648cd3c9-ec7f-47f4-9cf8-7817461ff785)

**Comment by Extravi** [comment]
Also, for the name change, I don't want confusion with LibreX or any other project, and I believe that "Aura Search" will be truly unique. Also, the letter "X" in the name is kind of odd. https://github.com/Extravi/tailsx/issues/67 I would also like to note that this project is not based on LibreX or any other project, as it is independent.

_Any reason why disabling IPv6 is a requirement? I'm also running my own instance and the frequent blocker is requests being blocked, while the popular alternatives, [whoogle-search](https://github.com/benbusby/whoogle-search) and LibreX (which this project is based on, it seems) do not have such requirements and can function totally fine._

_Originally posted by @taskylizard in https://github.com/Extravi/tailsx/issues/60#issuecomment-1736017302_

**Comment by amogusussy** [comment]
I could help with converting your index over when you eventually do implement it.

I just think that it would be good to have variety for users when it comes to what search engine they're using. Google is a notoriously bad company with censorship, so using other engines could help to mitigate that.
It would also allow for a backup if an instance gets rate limited by Google.
Also, it would bring the project up to par with other projects, such as SearxNG.

**Comment by Extravi** [comment]
the settings now will use javascript so you will need to work with that

**Comment by Extravi** [comment]
sure we can add other engines

**Comment by Extravi** [comment]
because the index things i am working on is taking a long time and idk when it will be done

**Comment by Extravi** [comment]
https://github.com/Extravi/araa-search/assets/98912029/5d21040a-06db-452b-89c9-0c085ba291a4

**Comment by Extravi** [comment]
that is the new settings system let me know if you like it and think it is better then before

**Comment by Extravi** [comment]
nvm wait pls hold off on this

**Comment by Extravi** [comment]
not sure how i feel about adding it

**Comment by Extravi** [comment]
because lots of code will have to be removed when i add in the index

**Comment by Extravi** [comment]
because both would have to work together

**Comment by Extravi** [comment]
yeah we need to hold off on this my project is not ready for it

**Comment by Extravi** [comment]
i need to take it slow for now and fix what needs fixing

**Comment by Extravi** [comment]
also i need to ensure every working correctly together down the line

**Comment by Extravi** [comment]
I have goals i set and need to reach first before i do anything like that or get there

**Comment by Extravi** [comment]
I want to maintain a level of quality and consistency for the time being, and adding other engines would break that.

**Comment by Extravi** [comment]
Recently I have been trying to clean up this project and its interface etc

**Comment by Extravi** [comment]
I am getting it ready for a few things first before i do anything I am mostly getting it ready for its own index

**Comment by Extravi** [comment]
as i said i have no eta because i need to add in stuff like this https://github.com/Extravi/araa-search/issues/52 first but something like an index for news wiki etc is coming

**Comment by Extravi** [comment]
thats why i was redoing settings etc

**Comment by Extravi** [comment]
i am getting it ready for something
