### ISSUE TITLE
My instance is up!

### ISSUE THREAD

**Issue by unstablemaple** [Extravi/araa-search#69]
Instance: [tailsx.seitan-ayoub.lol](https://tailsx.seitan-ayoub.lol)
Location: DE

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/aura-search/assets/98912029/f251d17a-5573-46c6-bbe6-63fc016089f2)


nice!

**Comment by Extravi** [comment]
btw i will be renaming tailsx soon https://github.com/Extravi/aura-search/issues/67 let me know what you think.

**Comment by Extravi** [comment]
thanks

**Comment by unstablemaple** [comment]
@Extravi Will do! Also, is there some sort of logo for the frontend so I can add it to my homepage?

**Comment by Extravi** [comment]
i will update the code with once done

**Comment by Extravi** [comment]
it adds a few things like this 

![image](https://github.com/Extravi/aura-search/assets/98912029/42bbbbe1-275c-4e82-bbd7-7f7d622850f4)

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/aura-search/assets/98912029/8e14eec7-5dfd-4a92-b295-29435bb561f4)

**Comment by Extravi** [comment]
I also replaced the background, let me know if you like it. Thanks.

**Comment by Extravi** [comment]
would you like me to add your instance to the instances list?

**Comment by unstablemaple** [comment]
> would you like me to add your instance to the instances list?
Yes, thank you! I will change the subdomain to the new name after you decide on one. I personally use Darkreader so I usually don't see the wallpaper, but the blur gives it an elegant look.

**Comment by unstablemaple** [comment]
Or you could have a colored "X" and have it inside a magnifying glass, which makes it "uppercase"

**Comment by Extravi** [comment]
thanks

**Comment by Extravi** [comment]
i think i will rename to Araa from TailsX

**Comment by unstablemaple** [comment]
@Extravi Before you add my instance, the video section on it doesn't even load, it just hangs then times out, any idea why this happens?

**Comment by Extravi** [comment]
do it load at any point?

**Comment by Extravi** [comment]
or did it just take some time

**Comment by unstablemaple** [comment]
It times out and gives me 504

**Comment by Extravi** [comment]
did you change the Invidious instance in config?

**Comment by Extravi** [comment]
i might not have api support on that instance or a working api

**Comment by Extravi** [comment]
https://yt.artemislena.eu/api/v1/search?q=cat

replace with the instance you want to use and test

**Comment by Extravi** [comment]
last update with the renaming has some bugs btw so i am working on fixing it in the next update with this (not complete)

trying my best to polish and clear up this project

![image](https://github.com/Extravi/araa-search/assets/98912029/b7e21ca4-2b78-49ab-bf1c-2bd6c77204fc)

**Comment by unstablemaple** [comment]
@Extravi, it's my [Invidious API](https://inv.seitan-ayoub.lol/api/v1/search?q=cat) instance and it works just fine, so the API shouldn't be a problem?

**Comment by Extravi** [comment]
can I see what you have typed in the configuration file for the api

**Comment by Extravi** [comment]
also send me a copy of the error on the server

**Comment by Extravi** [comment]
you can email me privately if you want extravi@extravi.dev

**Comment by Extravi** [comment]
alright bugs fixed from yesterdays update everything is all good now

**Comment by Extravi** [comment]
before updating your instance try it on any of my instances

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/b157a490-18a0-4d05-a879-542a3e726a41)
![image](https://github.com/Extravi/araa-search/assets/98912029/e7262592-568f-42cf-813a-c51e01b55fb9)
![image](https://github.com/Extravi/araa-search/assets/98912029/fae250a5-6e7a-4bc9-8f68-371482f5d88a)
![image](https://github.com/Extravi/araa-search/assets/98912029/ac6903d2-0906-4ac6-95c9-06b814ea26ec)

**Comment by unstablemaple** [comment]
@Extravi, bangs don't work unless you put them at the start of the query. Check [this](https://tailsx.extravi.dev/search?q=search+%21g+test&t=text).

**Comment by Extravi** [comment]
I know about that I think that's how bangs should work idk

**Comment by Extravi** [comment]
I don't really use bangs so idk

**Comment by unstablemaple** [comment]
> I don't really use bangs so idk

Realistically, most users will search with their privacy-respecting search engine and if they don't like the results they add a bang *at the end* of the query, so it makes sense to have it there.

**Comment by TEMtheLEM** [comment]
> @Extravi, bangs don't work unless you put them at the start of the query. Check [this](https://tailsx.extravi.dev/search?q=search+%21g+test&t=text).

@unstablemaple 

I did that by design; I thought of shebangs you'd see in scripting, and how they always came first at the top of all scripts.

I could possibly try changing it to what you're suggesting, but I don't feel that there's enough of a need to do so right now.

I'm open to hear what anyone else may feel about this.

(Also, thanks for hosting Araa/TailsX/another name pending maybe!)

**Comment by unstablemaple** [comment]
@Extravi @TEMtheLEM I have modified the `search()` function to have it parse bangs as desired: 

```      
   if BANG in query:
            query += " " # Simple fix to avoid a possible error 500
                         # when parsing the query for the bangkey.
            bang_index = query.index(BANG)
            bangkey = query[bang_index+1:query.index(" ", bang_index)].lower()
            if SEARCH_BANGS.get(bangkey) is not None:
                query = query.lower().replace(BANG + bangkey, "").lstrip()
                return app.redirect(SEARCH_BANGS[bangkey].format(query))
            # Remove the space at the end of the query.
            # The space was added to fix a possible error 500 when
            # parsing the query for the bangkey.
            query = query[:len(query) - 1]  
```
 That way, it will be able to detect the bangs wherever they are, in a query like `search !g test !yt` the function will redirect to google and will leave the YouTube bang as it is. My instance currently has the modified code for testing. If there are no bugs please inform me so I can make a pull request.

**Comment by Extravi** [comment]
does your instance use 1gb ram 2gb ram?

**Comment by Extravi** [comment]
you might need 2gb ram because with the system arra uses 1rb ram leaving 1gb free 

https://github.com/Extravi/araa-search/issues/74#issuecomment-1762371422
https://github.com/Extravi/araa-search/issues/74#issuecomment-1762383912
