### ISSUE TITLE
Araa search can now be used in up to 19 different languages; however, it's still a work in progress.

### ISSUE THREAD

**Issue by Extravi** [Extravi/araa-search#74]
If you find any translation mistakes, please let me know. I am aware of some missing translations that will be fixed in a later update. Also, I am aware of interface bugs with some languages.

https://github.com/Extravi/araa-search/commit/621d16601ff32f073c7a8197c86e88d5d5f1ce93
https://github.com/Extravi/araa-search/commit/54d5f561256a3c8598c4676901a6d7b0de3bd816

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/81204e17-6992-4348-807c-0e0dc9390951)

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/397197a9-96c2-4063-8b04-9e6d2003b3dd)

**Comment by Extravi** [comment]
If you have feedback, put it here, please. Thanks.

**Comment by pathia** [comment]
Hey, I'm testing with it. It seems the settings won't save. So to reproduce go to the hamburger menu and select for example French or Dutch. Whenever re-opening the hamburger menu the dropdown reverted to any language.
PS I'm using the docker hub image.

**Comment by Extravi** [comment]
clear your site cookie it won't save because it's a rewrite of previous settings

**Comment by Extravi** [comment]
also if you disable and re-enable JavaScript you will need to clear your cookies again because the cookies used aren't the same

**Comment by Extravi** [comment]
so please don't disable JavaScript it breaks stuff so don't disable JavaScript please as it breaks stuff

**Comment by Extravi** [comment]
that's why I have a warning next to disable JavaScript

**Comment by amogusussy** [comment]
If you enter a query that doesn't return any results, the text is still untranslated, saying this:
```
Your search 'example' came back with no results.
Try rephrasing your search term and/or recorrect any spelling mistakes.
```
It's at the bottom of all the different results pages.
Also, the expanded images statements (like 'View source:') aren't translated.

**Comment by amogusussy** [comment]
And the next/previous buttons at the bottom

**Comment by Extravi** [comment]
yeah I am aware

**Comment by pathia** [comment]
I don't see the application setting any cookies. Also, I just tested and It does work on https://tailsx.extravi.dev 
I currently run this on a local ip btw

**Comment by Extravi** [comment]
I will translate more later

**Comment by Extravi** [comment]
> I don't see the application setting any cookies. Also, I just tested and It does work on https://tailsx.extravi.dev 
> I currently run this on a local ip btw

clear your site cookies for the local application in your browser

**Comment by Extravi** [comment]
also make sure not to click disable JavaScript

**Comment by Extravi** [comment]
keep JavaScript enabled

**Comment by pathia** [comment]
> also make sure not to click disable JavaScript

I've seen no reason to disable it in the first place. Haven't touched that...

**Comment by Extravi** [comment]
are you using firefox or chrome?

**Comment by pathia** [comment]
firefox

**Comment by Extravi** [comment]
> firefox

https://youtu.be/H_MBoOEa3V4

watch from 1:09

**Comment by Extravi** [comment]
video is slightly outdated but it should work even on local applications

**Comment by pathia** [comment]
I understand but as I said my instance doesn't set any cookies. Not sure why. Could it be becasue it's running on http and on a local ip ?
(I also have DOMAIN set to 192.168.x.x in the .env file)

**Comment by Extravi** [comment]
i don't know how to use docker nor do I maintain the docker file @TEMtheLEM does

**Comment by Extravi** [comment]
I just write the code for the project

**Comment by Extravi** [comment]
and my instances don't run docker

**Comment by Extravi** [comment]
> I understand but as I said my instance doesn't set any cookies. Not sure why. Could it be becasue it's running on http and on a local ip ?
> (I also have DOMAIN set to 192.168.x.x in the .env file)

try it in a private browser window

**Comment by pathia** [comment]
I understand. I guess I'm running on older code then. I see the docker code was updated Oct 10, 2023 at 5:12 pm

**Comment by pathia** [comment]
Aha, I indeed see I'm running a different commit then your instance. Mine is cf5eb74e736ba3beba2250b2fd7334a69aa849cf

**Comment by Extravi** [comment]
also that docker image might have some unofficial changes I didn't make it different defaults

**Comment by TEMtheLEM** [comment]
Yeah sorry bout that. Haven't yet updated the public Docker image because of school. I'll be sure to do so when I can. @pathia

**Comment by Extravi** [comment]
> Aha, I indeed see I'm running a different commit then your instance. Mine is cf5eb74e736ba3beba2250b2fd7334a69aa849cf 
> 

yeah that's outdated the docker image needs to update

**Comment by Extravi** [comment]
ask @TEMtheLEM

**Comment by Extravi** [comment]
nvm he's here now

**Comment by pathia** [comment]
> Yeah sorry bout that. Haven't yet updated the public Docker image because of school. I'll be sure to do so when I can. @pathia

Please don't excuse. School has a higher priority. Don't rush the update, it's almost bedtime over here.
I'll try again in the next few days. Thank you!

**Comment by Extravi** [comment]
yeah same thing I am also a student

**Comment by Extravi** [comment]
so I work on this project when I can

**Comment by Extravi** [comment]
that's why the other translations are coming later

**Comment by Extravi** [comment]
> nvm he's here now 

yeah I am on my phone and it doesn't update instantly

**Comment by pathia** [comment]
I've seen a lot of commits and other activity. Thank you both for all the effort you put in to this.
If you need help for the Dutch translations let me know. I can help.

**Comment by Extravi** [comment]
thank you and np

**Comment by Extravi** [comment]
wip added more language support https://github.com/Extravi/araa-search/commit/ee8fa269630568cc7dcc9b616bc746d5304e78b5

**Comment by Extravi** [comment]
This is a work in progress, so it will improve over time. At least I have it working as of now, for the most part.

This will be getting a rewrite to correctly support more languages and not highlight unnecessary text.
```python
# search highlights
def highlight_query_words(string, query):
    query_words = [re.escape(word) for word in query.lower().split()]
    words = string.split()
    highlighted = []
    query_regex = re.compile('|'.join(query_words))
    highlighted_words = []
    for word in words:
        cleaned_word = word.strip().lower()
        escaped_word = escape(word)
        if query_regex.search(cleaned_word) and cleaned_word not in highlighted:
            highlighted_words.append(Markup(f'<span class="highlight">{escaped_word}</span>'))
            highlighted.append(cleaned_word)
        else:
            highlighted_words.append(escaped_word)
    return Markup(' '.join(highlighted_words))
    ```

**Comment by Extravi** [comment]
Before:
![image](https://github.com/Extravi/araa-search/assets/98912029/cdedc3cc-2daf-4eee-86d8-5e9f76ff28f7)
After:
![image](https://github.com/Extravi/araa-search/assets/98912029/2d7ce088-147f-426d-9d64-69060b68542b)
Before:
![image](https://github.com/Extravi/araa-search/assets/98912029/02f89198-b39e-40f5-b353-6db96d179309)
After:
![image](https://github.com/Extravi/araa-search/assets/98912029/d8267c3b-535b-44da-b027-3f0e5c0150a7)

**Comment by Extravi** [comment]
all languages got an improvement for search highlights

**Comment by Extravi** [comment]
you can also misspell and it will still correct you in the highlights to put this into context searxng does not do this 

![image](https://github.com/Extravi/araa-search/assets/98912029/1cc7cc28-8328-4ebf-9117-27464d21d1f1)

![image](https://github.com/Extravi/araa-search/assets/98912029/5d974781-2309-4a93-a2e3-8edb761f5c00)

**Comment by Extravi** [comment]
Before:
![image](https://github.com/Extravi/araa-search/assets/98912029/b81d3bb8-49b6-4a8c-a6f5-88ef9ce77066)
After:
![image](https://github.com/Extravi/araa-search/assets/98912029/2602615b-c91a-45fe-914c-691f71ce1821)

**Comment by Extravi** [comment]
it will now try to avoid highlighting unnecessary text

**Comment by Extravi** [comment]
it also understand context now 
Before:
![image](https://github.com/Extravi/araa-search/assets/98912029/92c8cb5d-53cf-49b9-a783-eb6c1f9da1f0)
After:
![image](https://github.com/Extravi/araa-search/assets/98912029/8fc043ee-5e30-4b46-9df1-0ba8ef179c69)

**Comment by Extravi** [comment]
Before:
![image](https://github.com/Extravi/araa-search/assets/98912029/0a9de85b-eade-4a5a-82f0-4dab107cc6b5)
After:
![image](https://github.com/Extravi/araa-search/assets/98912029/89bba16e-c297-437c-90fe-126c31290783)

**Comment by Extravi** [comment]
it understands what to highlight unlike before

**Comment by Extravi** [comment]
language support will be very important in this project and overall user experience and ease of use

**Comment by Extravi** [comment]
> it also understand context now Before: ![image](https://user-images.githubusercontent.com/98912029/274802878-92c8cb5d-53cf-49b9-a783-eb6c1f9da1f0.png) After: ![image](https://user-images.githubusercontent.com/98912029/274802853-8fc043ee-5e30-4b46-9df1-0ba8ef179c69.png)

Duckduckgo and others cant do that but google can

![image](https://github.com/Extravi/araa-search/assets/98912029/3186b502-8bd4-451a-8234-98fbd3984a21)
![image](https://github.com/Extravi/araa-search/assets/98912029/e6ad443a-be7e-4186-8ffa-6ef4a6722405)
![image](https://github.com/Extravi/araa-search/assets/98912029/eb181c49-5f0d-4dad-b8fd-a965069559b5)

**Comment by Extravi** [comment]
its been added and some auto lang stuff

**Comment by Extravi** [comment]
idk try it and let me know what you think

**Comment by Extravi** [comment]
araa search will now need a minimum of 2 gb of ram now due to yesterdays update 
![image](https://github.com/Extravi/araa-search/assets/98912029/3e62343c-ea7f-4c48-9ff7-c3f449893ffe)

**Comment by Extravi** [comment]
the above image is with 1gb ram

**Comment by Extravi** [comment]
i had to remove the ams instance due to cost and the cost to run this and upgrade fra and nyc to 2gb ram amd

**Comment by Extravi** [comment]
alright with 2 gb ram its fine 
fra
![image](https://github.com/Extravi/araa-search/assets/98912029/31b5d5e6-fd5b-4245-8279-bd116b676fc3)
nyc
![image](https://github.com/Extravi/araa-search/assets/98912029/5cf93537-22df-4184-8829-a1d7f58f4e7f)
