### ISSUE TITLE
User feedback.

### ISSUE THREAD

**Issue by Extravi** [Extravi/araa-search#77]
Is the user interface on the desktop on par with what you would expect with closed-source options for search, text, videos, settings, etc., excluding image search? If not, why? And what can I improve within the interface?

Do you think Araa Search is quite accessible and polished? For the most part, is it easy to use and easy to understand what's going on inside menus and drop-downs, like quick settings added to the search navigation bar? With visual clues (the 3 lines), do you know it's there and that you can interact with it? Is the accuracy of search highlights sufficient and well done for both Latin text and others like Japanese, Chinese, and Korean?

If there is anything you can change with the interface, what would it be? If you were to give the interface a score out of 10, how would it compare to closed-source options?

Quick settings:
![image](https://github.com/Extravi/araa-search/assets/98912029/f98d4930-6c16-48cb-be34-6070d808c417)
Search highlights:
q=green+tea+benefits&t=text
![image](https://github.com/Extravi/araa-search/assets/98912029/5ecb216f-41fd-473c-93e6-f29879b5bbc0)
q=goggle&t=text
![image](https://github.com/Extravi/araa-search/assets/98912029/623413fe-3cf9-4250-9cc3-4d74912ea841)

**Comment by amogusussy** [comment]
One issue is that the highlighted words include the punctuation (? after tea).

Another issue is that changing themes in the drop down menu refreshes the page. I think it should do it through javascript, without needing a refresh.

**Comment by Extravi** [comment]
> One issue is that the highlighted words include the punctuation (? after tea).

That does not seem to be an issue. I programmed it to highlight partial matches using the fuzzy, and that uses
https://en.wikipedia.org/wiki/Levenshtein_distance

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/266e3560-e289-472c-b705-265dcadc09ca)

**Comment by Extravi** [comment]
> Another issue is that changing themes in the drop down menu refreshes the page. I think it should do it through javascript, without needing a refresh.

When it refreshs the page it saves all current unsaved settings in settings so that might not be an issue idk.

**Comment by Extravi** [comment]
> > One issue is that the highlighted words include the punctuation (? after tea).
> 
> That does not seem to be an issue. I programmed it to highlight partial matches using the fuzzy, and that uses
> https://en.wikipedia.org/wiki/Levenshtein_distance
> 
> 

but this here is working correctly
