### ISSUE TITLE
Image search redirects to homepage

### ISSUE THREAD

**Issue by joshcangit** [Extravi/araa-search#87]
Searching for images redirects to `https://tailsx.extravi.dev/search` but search is empty.

**Comment by Extravi** [comment]
its not blocked atm tho

**Comment by Extravi** [comment]
![image](https://github.com/Extravi/araa-search/assets/98912029/cbe90a11-fb35-4044-b5ec-65aa71cab6d8)

**Comment by joshcangit** [comment]
Does Qwant block or limit this kind of 3rd party access?
I wonder if there's possible some workaround?

**Comment by Extravi** [comment]
i already use workarounds the ip just got blocked because someone was spamming my server
