### ISSUE TITLE
suggest improvements and give me ideas pls 

### ISSUE THREAD

**Issue by Extravi** [Extravi/araa-search#91]

**Comment by amogusussy** [comment]
You said in #54 that you would rewrite the pr for efficiency, so maybe you could do that.

**Comment by skynet2982** [comment]
First, thanks a lot for this amazing tool.

Some suggestion I have:
- Move code to [Codeberg](https://codeberg.org/) which is Open Source and maintained by an assiocation https://docs.codeberg.org/getting-started/what-is-codeberg/#what-is-codeberg-e.v.%3F (and not close source and owned by Microsoft, like Github). 
- Improve customization:
  - We shoud be able change the following text 
<img width="632" alt="Screenshot 2023-11-20 at 16 31 15" src="https://github.com/Extravi/araa-search/assets/7713432/4bcdc266-cdb7-47d1-85ae-85687a893484">
<img width="84" alt="Screenshot 2023-11-20 at 16 33 18" src="https://github.com/Extravi/araa-search/assets/7713432/22267241-3e28-49da-8725-f3896b5b030f">. 

- We should be able to remove the foot of the page
  - The link to the current instance does not make sense (your already are on the instance you want when you see this page)
<img width="779" alt="image" src="https://github.com/Extravi/araa-search/assets/7713432/15faed52-210b-43fb-b0f6-ae551b71a4e7">
- The commit should be removed, it is not useful for users.
- Maybe keep link to the repo (but for my you should let the admin of the instance choose).  
- Settings are duplicated, you already can find the settings on the right of the page.

**Comment by Extravi** [comment]
I am not going to move the source code away from GitHub

**Comment by Extravi** [comment]
I can add a setting to hide the commit thing inside of settings

**Comment by Extravi** [comment]
Settings are duplicated that's a quick menu with less settings

**Comment by Extravi** [comment]
the instance admin can already pick repo link in config

**Comment by Extravi** [comment]
> Settings are duplicated that's a quick menu with less settings

![image](https://github.com/Extravi/araa-search/assets/98912029/d520355f-13d3-4f2d-90f7-1feedff22803)
![image](https://github.com/Extravi/araa-search/assets/98912029/a0d65f6f-6a3f-40f7-9c42-2610738782f4)

**Comment by Extravi** [comment]
> the instance admin can already pick repo link in config

https://github.com/Extravi/araa-search/blob/ed29825178befb2def416525eadef3eabcbc66b4/_config.py#L10C1-L10C6

**Comment by Extravi** [comment]
less people use codeberg i dont want to move there also i have already been using github for years

**Comment by Extravi** [comment]
> First, thanks a lot for this amazing tool.
> 
> Some suggestion I have:
> 
>     * Move code to [Codeberg](https://codeberg.org/) which is Open Source and maintained by an assiocation https://docs.codeberg.org/getting-started/what-is-codeberg/#what-is-codeberg-e.v.%3F (and not close source and owned by Microsoft, like Github).
> 
>     * Improve customization:
>       
>       * We shoud be able change the following text
> 
> 
> <img alt="Screenshot 2023-11-20 at 16 31 15" width="632" src="https://user-images.githubusercontent.com/7713432/284314224-4bcdc266-cdb7-47d1-85ae-85687a893484.png"> <img alt="Screenshot 2023-11-20 at 16 33 18" width="84" src="https://user-images.githubusercontent.com/7713432/284314296-22267241-3e28-49da-8725-f3896b5b030f.png">.
> 
>     * We should be able to remove the foot of the page
>       
>       * The link to the current instance does not make sense (your already are on the instance you want when you see this page)
> 
> 
> <img alt="image" width="779" src="https://user-images.githubusercontent.com/7713432/284314855-15faed52-210b-43fb-b0f6-ae551b71a4e7.png">
> 
>     * The commit should be removed, it is not useful for users.
> 
>     * Maybe keep link to the repo (but for my you should let the admin of the instance choose).
> 
>     * Settings are duplicated, you already can find the settings on the right of the page.

if you're talking about the settings link in the footer its there for no js users 
![image](https://github.com/Extravi/araa-search/assets/98912029/aa124392-633d-4fff-a5b0-ded1494008e3)

**Comment by skynet2982** [comment]
> less people use codeberg i dont want to move there also i have already been using github for years

Of course, everybody is using Github for years that's exactly why Microsoft bought it and now there are using all the code hosted on it to improve there AI and make money with it. I won't insist with that idea but think about it ;)

**Comment by amogusussy** [comment]
>Settings are duplicated

Its also there for non-JS users, since the one at the top is generated using javascript.

Also, its useful for if youre at the bottom and want to access settings, scrolling up is inconvenient.

**Comment by Extravi** [comment]
> > less people use codeberg i dont want to move there also i have already been using github for years
> 
> Of course, everybody is using Github for years that's exactly why Microsoft bought it and now there are using all the code hosted on it to improve there AI and make money with it. I won't insist with that idea but think about it ;)

yeah i know and i dont really care when the service is provided for free
